### ISSUE TITLE
1.19 Crash on startup 

### ISSUE THREAD

**Issue by Tyrius1** [wendall911/Homeostatic#1]
https://pastebin.com/ARL91KRt

**Comment by wendall911** [comment]
Thanks for reporting. Looks like I'm not checking if Serene Seasons is installed. I'll fix tomorrow and push out an update. Thanks for the report!

**Comment by wendall911** [comment]
Fixed in https://github.com/wendall911/Homeostatic/commit/54e79e830e6ef08bccef9af59c094896292149e1 and released on CurseForge. Thanks for the report! I just checked to see if it was loaded after calling Serene Seasons code. Oops.
