### ISSUE TITLE
I translated it into Simplified Chinese

### ISSUE THREAD

**Issue by ArchiDreamZ** [wendall911/Homeostatic#12]
The version is 2.6.3.0
It took me a long time to translate, the contents of the tutorial book have all been translated, and make sure there are no translation errors.
If the format is affected in github, I also sent the file below, the json cannot be uploaded, so I compressed it.

{
  "itemGroup.homeostatic.items": "Homeostatic(稳态)",
  "effect.homeostatic.thirst": "脱水",
  "block.homeostatic.purified_water_fluid": "纯净水",
  "death.attack.dehydration": "%1$s 变成了干巴的 %1$s",
  "death.attack.dehydration.player": "%1$s 在与 %2$s 战斗时变成了干巴的 %1$s",
  "death.attack.heat": "%1$s 死于烫伤",
  "death.attack.heat.player": "%1$s 在与 %2$s 战斗时死于烫伤",
  "death.attack.hyperthermia": "中暑夺走了可怜的 %1$s",
  "death.attack.hyperthermia.player": "在与 %2$s 战斗时，中暑夺走了可怜的 %1$s",
  "effect.thirst": "脱水",
  "fluid_type.homeostatic.purified_water_type": "纯净水",
  "info.homeostatic.book.education.body_temp.intro": "更多信息即将到来 ...",
  "info.homeostatic.book.education.body_temp.name": "教程：体温",
  "info.homeostatic.book.education.desc": "本节专门针对那些想公开论证跑来跑去可以产生足够的身体热量，即使在你又湿又冷并且只穿着 T 恤和裤子（即使你有点超人）时也很重要。 这太愚蠢了。$(br)$(br)如果需要，请参阅以下页面以了解其实际工作原理。提示：无论你跳来跳去或跑多少，如果又湿又冷，你都会被冻死。此外，非常热的东西会烫伤、煮沸或烧伤你……",
  "info.homeostatic.book.education.environment.intro": "更多信息即将到来 ...",
  "info.homeostatic.book.education.environment.name": "教程：环境",
  "info.homeostatic.book.education.hydration.intro": "更多信息即将到来 ...",
  "info.homeostatic.book.education.hydration.name": "教程：口渴值",
  "info.homeostatic.book.education.name": "教程",
  "info.homeostatic.book.gameplay.body_temp.details": "有几个因素用于计算体温:$(br)$(li)环境温度.$(li)盔甲 - 详情见后页.$(li2)$(l:homeostatic:gameplay/body_temp#insulation)隔热$()$(li2)$(l:homeostatic:gameplay/body_temp#radiation_protection)热辐射防护$()$(li2)$(l:homeostatic:gameplay/body_temp#waterproofing)防水$()$(li)$(l:homeostatic:gameplay/body_temp#wetness)湿度$()$(li2)玩家的干湿程度决定了他们降温或升温的速度.$(li)$(l:homeostatic:gameplay/body_temp#scalding)烫伤$() / $(l:homeostatic:gameplay/body_temp#hyperthermia)中暑$()$(li)$(l:homeostatic:gameplay/body_temp#hypothermia)冻伤/失温$()",
  "info.homeostatic.book.gameplay.body_temp.hyperthermia.intro": "当身体温度高于 106°F 或 41°C 时，可能会发生中暑。",
  "info.homeostatic.book.gameplay.body_temp.hyperthermia.title": "中暑",
  "info.homeostatic.book.gameplay.body_temp.hypothermia.intro": "当身体温度低于 95°F 或 35°C 时，可能会发生失温。",
  "info.homeostatic.book.gameplay.body_temp.hypothermia.title": "冻伤/失温",
  "info.homeostatic.book.gameplay.body_temp.insulation.text": "任何装备都可以隔热。隔热的部件越多，玩家的隔热效果就越好。有关合成表，请参阅 JEI/REI。",
  "info.homeostatic.book.gameplay.body_temp.insulation.title": "隔热",
  "info.homeostatic.book.gameplay.body_temp.intro": "上面的箭头指向体温在HUD中的位置。可以华氏度或摄氏度显示。",
  "info.homeostatic.book.gameplay.body_temp.name": "体温",
  "info.homeostatic.book.gameplay.body_temp.radiation_protection.text": "任何装备都可以添加热辐射防护。添加到多个部件以实现最大程度的防护。$(br)此外，耐火性可充分保护玩家免受热辐射源的伤害。",
  "info.homeostatic.book.gameplay.body_temp.radiation_protection.title": "热辐射防护",
  "info.homeostatic.book.gameplay.body_temp.remove_insulation.text": "隔热可以从任何装备上移除。合成表没有写入 JEI/REI。",
  "info.homeostatic.book.gameplay.body_temp.remove_insulation.title": "移除隔热",
  "info.homeostatic.book.gameplay.body_temp.remove_radiation_protection.text": "热辐射防护可以从任何装备上移除。合成表没有写入 JEI/REI。",
  "info.homeostatic.book.gameplay.body_temp.remove_radiation_protection.title": "移除热辐射防护",
  "info.homeostatic.book.gameplay.body_temp.remove_waterproof.text": "防水可以从任何装备上移除。合成表没有写入 JEI/REI。",
  "info.homeostatic.book.gameplay.body_temp.remove_waterproof.title": "防水",
  "info.homeostatic.book.gameplay.body_temp.scalding.intro": "当玩家靠近140°F 或 60°C以上的极热源时，可能会发生烫伤。",
  "info.homeostatic.book.gameplay.body_temp.scalding.title": "烫伤",
  "info.homeostatic.book.gameplay.body_temp.title": "身体 °F/C HUD",
  "info.homeostatic.book.gameplay.body_temp.waterproof.text": "防水可以添加到任何装备上。添加到多个部件以增加防水程度。",
  "info.homeostatic.book.gameplay.body_temp.waterproof.title": "防水",
  "info.homeostatic.book.gameplay.body_temp.wetness.details": "玩家的干湿程度决定了 $(l:homeostatic:gameplay/body_temp)体温$() 降低的速度. 这可能是好事也可能是坏事，视情况而定:$(li)炎热时，潮湿或在水中可以帮助玩家快速降温。$(li)寒冷时，潮湿会增加玩家冻死的风险。$(li2)寻找庇护所或为盔甲添加 $(l:homeostatic:gameplay/body_temp#waterproofing)防水$() 对于保持干燥至关重要。",
  "info.homeostatic.book.gameplay.body_temp.wetness.intro": "弄湿时，水滴会覆盖在屏幕边缘，如上图所示。",
  "info.homeostatic.book.gameplay.body_temp.wetness.title": "湿度",
  "info.homeostatic.book.gameplay.desc": "游戏玩法通过多种机制得到增强。$(li)环境温度$(li)体温$(li2)湿度$(li2)中暑/烫伤$(li2)失温/冻伤$(li2)简单地说就是身体对环境温度的反应。$(li2)通过增强你的盔甲来保护自己，即使只穿盔甲也有帮助。$(li)口渴值$(li2)你现在又渴又饿。保持水分！",
  "info.homeostatic.book.gameplay.environment.details": "有几个因素可用于计算局部温度：$(br)$(li)当前温度和来自周围生物群落的影响。$(li)日照。$(li)热辐射源：例如岩浆、火把、点燃的熔炉等。$(li)海拔：山顶凉爽，地下温度更稳定。",
  "info.homeostatic.book.gameplay.environment.intro": "上面的箭头指向HUD中局部温度的位置。可以华氏度或摄氏度显示。",
  "info.homeostatic.book.gameplay.environment.name": "环境温度",
  "info.homeostatic.book.gameplay.environment.title": "环境 °F/C HUD",
  "info.homeostatic.book.gameplay.hydration.details": "补水有几种方法：$(br)$(li)徒手喝水。$(li2)蹲下并右键任何水源，你可以直接喝水。这可能会导致负面状态影响。$(li)准备一个水袋。合成表和详细信息在以下页面上。$(li)吃有水分的食物或饮料。如果手持任何含水物品，一个小的预览会在水分条上闪烁(类似苹果皮)。",
  "info.homeostatic.book.gameplay.hydration.intro": "上面的箭头指向水分条。这类似于饥饿，较亮的高光表示饱和度。",
  "info.homeostatic.book.gameplay.hydration.leather_flask.smelting.text": "要净化水袋中的脏水，有以下几种方法：$(li)在熔炉中烧（如上所示）$(li)用营火烹制 $(li)用烟熏炉熏制$(li)使用滤水纸(合成表在下一页）",
  "info.homeostatic.book.gameplay.hydration.leather_flask.smelting.title": "皮革水袋净化",
  "info.homeostatic.book.gameplay.hydration.leather_flask.text": "皮革水袋在水资源有限的环境中至关重要。要填充，只需与任何水源方块交互，它就会被“填充”。然而，这是脏水。请参阅下页进行净化。",
  "info.homeostatic.book.gameplay.hydration.leather_flask.title": "皮革水袋",
  "info.homeostatic.book.gameplay.hydration.leather_flask_water_filter.text": "只需将装满水的水袋与滤水纸合成起来，即可制作一瓶纯净水。",
  "info.homeostatic.book.gameplay.hydration.leather_flask_water_filter.title": "皮革水袋净化",
  "info.homeostatic.book.gameplay.hydration.name": "补水/口渴",
  "info.homeostatic.book.gameplay.hydration.title": "口渴值 HUD",
  "info.homeostatic.book.gameplay.hydration.water_filter.text": "滤水纸也可用于合成以过滤皮革水袋中的脏水。",
  "info.homeostatic.book.gameplay.hydration.water_filter.title": "滤水纸",
  "info.homeostatic.book.gameplay.name": "玩法",
  "info.homeostatic.book.intro": "不违反逻辑的温度和水分变化...$(br)$(li) $(l:homeostatic:education/environment)环境$()温度受 $(l:https://simple.wikipedia.org/wiki/Thermal_radiation)热辐射$()影响, 比如太阳、岩浆、营火等等。$(li)必须保持体温，否则你会得到 $(l:https://simple.wikipedia.org/wiki/Hyperthermia)中暑$() 或 $(l:https://simple.wikipedia.org/wiki/Hypothermia)失温$() $(li)补水是生存所必需的。",
  "info.homeostatic.book.subtitle": "关于温度和水",
  "item.homeostatic.book": "Homeostatic(稳态)mod教程书",
  "item.homeostatic.leather_flask": "皮革水袋",
  "item.homeostatic.purified_water_bucket": "纯净水桶",
  "item.homeostatic.thermometer": "温度计",
  "item.homeostatic.water_filter": "滤水纸",
  "tooltip.insulation": "隔热",
  "tooltip.radiation_protection": "热辐射防护",
  "tooltip.thermometer": "Thermovision",
  "tooltip.water_container.empty": "空",
  "tooltip.waterproof": "防水"
}

This is the file：
[zh_cn.zip](https://github.com/wendall911/Homeostatic/files/10424266/zh_cn.zip)

I want to localize a Chinese name for this mod，What do you think of the name "稳态".This word is a biological term in Chinese, and the meaning is also very consistent with the intention of your mod

**Comment by Athurrender** [comment]
老兄你应该把这个发到Pull requests。但是我得说这个lang还有问题，我发的issue作者还没解决，所以我也一直还没上传汉化，等作者解决了再说...

**Comment by ArchiDreamZ** [comment]
lang缺失的可以自己加上的，同时我也提醒了作者加上

**Comment by Athurrender** [comment]
> 

确实，不过我更关心HUD的问题，虽然能直接看温度，不过冷得要死温度球还是灰的真的怪😂而且靠改材质没有用只能改代码

**Comment by ArchiDreamZ** [comment]
> > 
> 
> 确实，不过我更关心HUD的问题，虽然可以直接看温度，不过冷得要死温度球还是灰的真怪😂而靠改材料没有用只能改代码

但是我在1.19.2是完全正常的，这个很奇怪

**Comment by wendall911** [comment]
@Athurrender @ArchiDreamZ Can you both confirm that the PR translation is accurate? I will add this to the mod if so. I generate this file, so can't merge this directly, but can add the text if I can get a confirmation. I've also updated the mod for 1.19.4 and 1.20.1
