### ISSUE TITLE
Wrong HUD display order

### ISSUE THREAD

**Issue by Sam-Chai** [wendall911/Homeostatic#16]
![image](https://user-images.githubusercontent.com/29940426/215259077-61d2765f-80be-47f2-be27-340263155699.png)

Please look at the picture, the text component is behind the water and temp HUD, and some long text hasn't seen because this problem.
For normally, the text component is the highest level on the HUD. Please fix it, thanks!

**Comment by wendall911** [comment]
This is resolved now in all versions. Thanks for reporting.
