### ISSUE TITLE
Request - Configurable hydration loss when sleeping

### ISSUE THREAD

**Issue by NostalJay** [wendall911/Homeostatic#17]
I think this would be a great option for players who want to make the early game a little more challenging.

**Comment by Athurrender** [comment]
Try somnia awoken,a mod that simulates the world while you sleep. works great with Homeostatic.You will even get hypothermia if you sleep in cold biomes without a heat sourse.

**Comment by Athurrender** [comment]
> I think this would be a great option for players who want to make the early game a little more challenging.


Try somnia awoken,a mod that simulates the world while you sleep. works great with Homeostatic.You will even get hypothermia if you sleep in cold biomes without a heat sourse.
