### ISSUE TITLE
how do i add thirst to modded objects

### ISSUE THREAD

**Issue by Thisguyneedshelp** [wendall911/Homeostatic#2]
is there maybe a datapack template i can use to add thirst values to modded foods and drinks.

**Comment by wendall911** [comment]
I don't currently have a mechanism for this, but will add something very soon! Thanks for asking. Do you have mods in mind? I can work on those specifically in my testing to make sure they work.

To be honest, this is a little more work to do this type of integration, but I will certainly do this, likely this week.

**Comment by Thisguyneedshelp** [comment]
well, theres a lot, i have croptopia, farmers delight, delightful, xerca, morecraft, and there are a bunch of others that probably have random items i wanted to add but dont worry about it

**Comment by wendall911** [comment]
Ok, great. I'll start working on this. Appreciate the feedback.

**Comment by Thisguyneedshelp** [comment]
oh, sorry to add to your workload but id also appreciate if you could make auto feeding from sophisticated backpacks fulfill thirst as well thatd also be great

**Comment by Thisguyneedshelp** [comment]
again sorry. but if you could make more than just the drinks in the mods provide thirst id really appreciate it, things like soup and fruits that are actually high in water content, and if it isnt too hard maybe even make it so eating hot soups warms you some and drinking cold beverages can cool you, i get if all of this is too much thanks anyways keep up the good work

**Comment by Thisguyneedshelp** [comment]
also i realized theres some foods in these mods so ill list them too ecologics, naturalists, bop, and otbyg

**Comment by wendall911** [comment]
Small update. I've just added block radiation as a datapack resource. I'm now implementing this for thirst. I need to work through how this will work for Sophisticated Backpacks still, but that will be last. I'll probably release with the datapack changes for block radiation and thirst once I have that completed.

Taking me a little bit here, as I'm doing this for both 1.18.2 and 1.19.x

**Comment by wendall911** [comment]
@Thisguyneedshelp I've updated with mod support for several of the ones you listed. Plus modpack support for hydration (drinkable) items, as well as, datapack support for radiation generating block (heat).

**Comment by wendall911** [comment]
I'll add some info to the wiki for this soon. In the meanwhile, take a look at: https://github.com/wendall911/Homeostatic/tree/1.19/src/generated/resources/data/minecraft/environment

**Comment by wendall911** [comment]
@Thisguyneedshelp I also confirmed that this works with Sophisticated Backpacks!

**Comment by Thisguyneedshelp** [comment]
thank you very very much, for whatever reason tough as nails is broken for 1.19 so you really saved me and my modpack

**Comment by wendall911** [comment]
I literally wrote this mod over frustration with TAN. Not only did he choose to close-source the mod, but it is just frustratingly bad in a lot of ways. I am hoping a few packs pick it up so I can continue to improve it. We've been playing it with the Tinkers' Survival modpack quite a bit and been getting positive feedback.

I still need to figure out how to get JEI to show the recipes for insulation/radiation resistance/water proofing for armor. JEI api for custom recipes changes like every other day, so it's hard to figure out. I think I might work on that next.
