### ISSUE TITLE
It Is Difficult to Get Close to Nether's Large Lava Lake

### ISSUE THREAD

**Issue by DarkgreenWorld** [wendall911/Homeostatic#26]
In fact, even if I put on a full set of armor with the function of preventing thermal radiation, I will soon be injured by overheating when I get close to this large Lava lake.This means that I can't cross Lava lake directly by any means, including taking Strider.
I think it is necessary to provide a more effective thermal radiation protection.

**Comment by wendall911** [comment]
The only additional method currently is through a fire resistance potion, which will bring you up to 100% radiation resistance if you have a full set of armor with radiation resistance. I will make sure to add this to the book. I"m still thinking on other ways to add potential resistance up to 100%. Currently armor with protection brings you up to 80%.
