### ISSUE TITLE
Purified water block rendering issue

### ISSUE THREAD

**Issue by Athurrender** [wendall911/Homeostatic#27]
Purified water block is not rendering correctly. it should use Translucent rendering like the water.
Not a texture problem for sure. 
And would it possible to add white underwater fog like water? 
![2023-07-27_21 42 52](https://github.com/wendall911/Homeostatic/assets/122013559/3cd11d50-12c3-4f74-9625-884c73497425)
![2023-07-27_21 42 55](https://github.com/wendall911/Homeostatic/assets/122013559/44a7cadb-9759-403f-b9d5-b0c694e368a1)
![2023-07-27_21 43 16](https://github.com/wendall911/Homeostatic/assets/122013559/d283e6ce-6ae1-42a5-9323-10a2b6ed1650)

**Comment by wendall911** [comment]
This is not an in-game item, only available via creative mode, as a water bucket item is required for liquids. This is not an issue. Please don't report creative mode issues, as the mod doesn't even function in creative mode.
