### ISSUE TITLE
The Temperature In Winter is Also 10 ℃, Which Seems Unreasonable

### ISSUE THREAD

**Issue by DarkgreenWorld** [wendall911/Homeostatic#29]
In snowy weather, the temperature should definitely be below 0 ℃.

**Comment by DarkgreenWorld** [comment]
By the way, it is best to translate 'insulation' in Chinese as '保温 'rather than '隔热' . There is an ambiguity in Chinese about '隔热', which cannot indicate whether it is for 'external thermal radiation' or 'internal thermal radiation' (although players should be able to determine the meaning through 'wool', it is best to accurately translate it)

**Comment by DarkgreenWorld** [comment]
By the way, it is best to translate 'insulation' as '保温' rather than '隔热' . There is an ambiguity in Chinese about '隔热', which cannot indicate whether it is for 'external thermal radiation' or 'internal thermal radiation' .Chinese users usually understand it as "radiation protection" rather than 'insulation'.(Although players should be able to determine its meaning through 'wool', because sweaters cannot help cool down in summer,but it is best to accurately translate it.)
When it comes to cooling down, adding ice water seems to be a good way, but ice water can quickly turn into ordinary water at high temperatures, so it seems like you need something like a thermos cup?

**Comment by wendall911** [comment]
Ok, the temperature system in the mod isn't a negotiation point. There are links on the README that can help. The system is in place to allow for seasons mods to work correctly and for biome temperature smoothing purposes.

As for the translations. It has nothing to do with this issue. There are others who provided the translation. Sumbit a PR and I will have them review. Please stop spamming the issue tracker. Use TAN if you want something that makes no sense for temperature, it works perfectly for that.
