### ISSUE TITLE
sorry but its crashing now 1.19 forge 41.1.0

### ISSUE THREAD

**Issue by Thisguyneedshelp** [wendall911/Homeostatic#3]
here's the logs https://mclo.gs/QI2Yoj5 ,it seems to crash whenever i try to drink something, sorry to put more on your plate

**Comment by Thisguyneedshelp** [comment]
hey so it turns out it might not be your mod causing the problem as i just crashed after having been hit, however seeing as i dont know what might be causing it i would be extremely grateful if youd help me anyways... heres the logs from the crash just now https://mclo.gs/ZhwHocx

**Comment by wendall911** [comment]
Error is from bettermuffling mod. It is probably happening when sounds are triggered, like drinking, getting hit,etc.

**Comment by wendall911** [comment]
Oh, hmm, you're using 1.19 ... I tested with 1.19.2. There was an API change with forge. Let me work with the deprecated method for now and it should work with 1.19. There may be other bugs, as I have nearly zero motivation to test with 1.19, as it isn't really very relevant unless there isn't any other choice in upgrading.

**Comment by wendall911** [comment]
Testing now with 1.19 to see if this fixes it and I'll push out. Highly recommend moving to 1.19.2, as 1.19 was out for like 30 seconds before 1.19.2 was released and it is an odd version to support. I don't mind making fixes, just I'm literally testing about 100 mods with 1.19.2, so it is rough to try and test.

**Comment by wendall911** [comment]
I'm just now realizing that this will not work for 1.19 ... there were breaking changes in forge and several of the methods I'm using are deprecated. So I would have to do a 1.19 specific branch. I'm going to push an update up setting the minimum version to 1.19.2. I'll work on getting something out for 1.19 if you need it, but it will probably be difficult to maintain. (I cannot understand why Forge still provided updates given they chose to make breaking changes)

I"m surprised it even launches for you. I get a crash on startup with 41.0.1

**Comment by wendall911** [comment]
Actually trying something that might work!

**Comment by wendall911** [comment]
Ok, found a workaround to still be able to support 1.19-1.19.2 ... I will still have a hard time testing, but give this a shot, as it worked for me:
https://www.curseforge.com/minecraft/mc-mods/homeostatic/files/3963056

I had to move back to using a deprecated method, but no worries for now. Let me know if you find any other issues, I'll be happy to fix.

**Comment by Thisguyneedshelp** [comment]
sorry to add so much to your plate and sorry i was unresponsive(was watching new dragonball movie(it was meh)), and thank you so much again

**Comment by Thisguyneedshelp** [comment]
and yeah unfortunately a lot of the mods i wanted arent 1.19.2 yet, so thanks again

**Comment by Thisguyneedshelp** [comment]
im sure i can fix it with a datapack but just so you know the glass of sparkling water isnt working for xerca

**Comment by Thisguyneedshelp** [comment]
also i assume since i dont see how there isnt a way to make cold things make you a bit colder and hot things warming you up

**Comment by wendall911** [comment]
Ok, for heat mechanics, this mod attempts to work how actual body mechanics work. There isn't any such thing as cold energy, only heat radiation sources, if it is cold, there is just simply a lack of heat. Heat radiation sources can be defined in datapack data like this: https://github.com/wendall911/Homeostatic/tree/1.19/src/generated/resources/data/minecraft/environment/block_radiation

The one thing I'm reluctant to expose is the biome temperatures. I've smoothed and normalized these to make some sort of sense. I can't do this via datapack because of how it is implemented, so I am holding off on that one for now.

Also, will push up a quick addition of the sparkling water addition.

**Comment by Thisguyneedshelp** [comment]
is that for items or just blocks

**Comment by wendall911** [comment]
Only for blocks at this point. We considered doing it for held items, but it was difficult to figure out game balance.

**Comment by wendall911** [comment]
I mean if you can carry several tons of stone in your pockets, why not 20 buckets of lava? :)

**Comment by wendall911** [comment]
@Thisguyneedshelp do you use discord? I have one for Tinkers' Survival that you can join if you have more comments/questions: https://discord.gg/PDpv8zzt
