### ISSUE TITLE
Heat source compatibility

### ISSUE THREAD

**Issue by Athurrender** [wendall911/Homeostatic#33]
I notice that there is only food compatibility but no heat source compatibility for other mods, would it be possible to add heat source compatibility for other mods like Farmer's delight and Create? It would be better if players could add compatibility via datapack by themselves.

**Comment by wendall911** [comment]
There are a few mods added already. This is already available via data
pack. I will document this and let you know.

**Comment by Athurrender** [comment]
That's great! I really appreciate it.

**Comment by wendall911** [comment]
Ok, I appreciate reminding me to document this stuff. I actually found a major bug in the 1.19 and 1.20 ports that caused the biome temperatures to not be applied correctly. That is fixed now. Documentation is updated in the wiki, but specific heat source datapack integration can be found here: https://github.com/wendall911/Homeostatic/wiki/Data-Pack-Customizations

If you have any specific requests for mods please let me know, I'll be happy to add it to future releases. Just make a new issue with mod integration feature request.

I already know I need to probably add support for create, but not sure exactly how that integration will work, as I haven't investigated how the Blaze Burner deals with "Lit" status.
