### ISSUE TITLE
Add Create Blaze Burner Block Radiation

### ISSUE THREAD

**Issue by wendall911** [wendall911/Homeostatic#34]

**Comment by adoetho** [comment]
He's specifically referring to an issue with Create, specifically this:
https://github.com/Creators-of-Create/Create/issues/6335 (my own post)

Might want to review this and patch it ASAP, since it bricks saves.

**Comment by wendall911** [comment]
Looks like they made a breaking change ... again. I will update against newer version and release soon. Thanks for the report!
