### ISSUE TITLE
[1.18.2-1.19.2] thirst effect display issue

### ISSUE THREAD

**Issue by Athurrender** [wendall911/Homeostatic#35]
1.18.2 and 1.19.2 version is still using ("effect.thirst": "Thirst",) in lang json,
but now ("effect.homeostatic.thirst": "Thirst",) is the correct one. 
Now thirst effect displays as this:
![2023-08-06_22 58 00](https://github.com/wendall911/Homeostatic/assets/122013559/2e7d23b4-7fc2-46b8-82c6-3f6d6ca246aa)

**Comment by Athurrender** [comment]
Created pull requests just now，is it already in the update list before？

**Comment by wendall911** [comment]
I'll fix this. I don't need a PR. Working on it now.

**Comment by Athurrender** [comment]
> 

OK

**Comment by wendall911** [comment]
Fix is released on both CurseForge and Modrinth. Thanks for letting me know!
