### ISSUE TITLE
It's not cold at all in Primal Winter, Are there any possible to be compatible?

### ISSUE THREAD

**Issue by JiuyeAyan** [wendall911/Homeostatic#36]
I'm playing with [_Primal Winter_](https://www.curseforge.com/minecraft/mc-mods/primal-winter), this mod makes the whole world in frozen.

And I add your mod Homeostatic. 
However, even in extream snow storm, my teperature is keeping still, it's not cold at all.
![image](https://github.com/wendall911/Homeostatic/assets/90959597/dcd56a56-1ee3-4bec-b87c-d9d4a9655041)

So I'm wondering are there any possible to be compatible to the _Primal Winter_?
Make this world much harder to survive in Primal Winter?

Thank u so much

**Comment by wendall911** [comment]
I will add support, not a problem. I'll let you know when I've added it. I have a couple other minor updates today I can include it with.

**Comment by wendall911** [comment]
Primal Winter doesn't touch the temperature system. So what I will do is make it so it sets all biomes to SNOW precipitation temperatures, and is always set to MID WINTER. Uses the same calculation for winter as Serene Seasons.

Will have a release out shortly.

**Comment by wendall911** [comment]
Ok, released on CurseForge and Modrinth for all versions. One thing of note. This is going to be really hard. Getting underground where it is warm will likely be vital for survival.

**Comment by JiuyeAyan** [comment]
Thank u so much! I'll give it a try :)

**Comment by wendall911** [comment]
There was an issue in the last build that I fixed. Please use the latest version 2.9.4.4, as 2.9.4.3 will not have correct temperatures.
