### ISSUE TITLE
Why can I prevent damage from low body temperature by wearing any leather armors?

### ISSUE THREAD

**Issue by Windavilin** [wendall911/Homeostatic#39]
I played version 2.9.9.4 of Homeostatic.Thank you for making the adjustments for Primal Winter, making my modpack more realistic and challenging.
But I wonder that why is it that even though my body temperature is already so low, I am still unharmed while wearing a leather helmet?
Through testing, other materials of armor with insulation properties did not have this effect.Is this a characteristic that leather armor should have in Homeostatic?
![image](https://github.com/wendall911/Homeostatic/assets/141706381/e476c868-62f1-47a5-b2be-9ba4a184e82f)

**Comment by Windavilin** [comment]
In addition, I found that in the new mechanism of Homeostatic, satiety clearing does not seem to cause damage to players.

This seems unique to Homeostatic 2.9.9.4.

I think it can reduce the frequency of damage caused by lack of satiety, but completely avoiding it is not good. This means that players can stay next to heat sources and live without eating anything.

**Comment by wendall911** [comment]
I know about the leather armor thing. It is the Minecraft mechanic for frost damage. I could potentially change it, but it is intentional. As for not taking damage with food. That may be a Minecraft bug when wearing leather armor and freezing. Let me test. The mod is not doing anything special here. I will do some testing and see what the issue is.

What version of Minecraft are you using specifically?

**Comment by Windavilin** [comment]
> I know about the leather armor thing. It is the Minecraft mechanic for frost damage. I could potentially change it, but it is intentional. As for not taking damage with food. That may be a Minecraft bug when wearing leather armor and freezing. Let me test. The mod is not doing anything special here. I will do some testing and see what the issue is.
> 
> What version of Minecraft are you using specifically?
I use Minecraft 1.19.2, and the version of Forge is 43.2.21.

**Comment by Windavilin** [comment]
I use Minecraft 1.19.2, and the version of Forge is 43.2.21.

**Comment by wendall911** [comment]
Ok, the not taking damage thing when out of food is not from this mod. Are you using Healing Campfires mod? That would explain. It does appear that hunger is reduced very quickly (this is because of shivering).

- Ok, I think I should set the maximum amount of food that is reduced quite a bit lower.
- I would need to bypass the Minecraft mechanic when using leather armor to ignore freezing... thoughts?

**Comment by wendall911** [comment]
I am going to reduce the maximum hunger loss by half. I'm looking into what to do about the freezing bypass for leather armor.

**Comment by Windavilin** [comment]
Thank you for your willingness to try my question! But when I use Homeostatic version 2.6.8.2, it is normal for me to suffer damage when my satiety is 0. I haven't added any modules for healing campfires and modifying satiety mechanisms, perhaps there are some undiscovered conflicts? I will try it with you.

**Comment by Windavilin** [comment]
Do you know if leather armor's durability will be damaged when immune to cold damage? If so, I look forward to you adjusting the damage speed to a fast enough level.

**Comment by Windavilin** [comment]
I think your adjustment to the maximum hunger loss is excellent. But what do you think about adjusting to the hunger threshold (below 6)? I feel that this will make the negative effects of the cold even more severe and more realistic.

**Comment by wendall911** [comment]
Oh, that makes a lot of sense. Adjusting to the threshold is excellent.

As for the insulation bypass of leather armor, there is a tag: FREEZE_IMMUNE_WEARABLES that sets the ignore freeze. You could override this in your modpack to remove the characteristic from leather armor. I'm not sure I want to remove this, as it is the default mechanic for Minecraft, which is something I was trying to honor.

**Comment by Windavilin** [comment]
Okay, I got it

Thank you very much. Your efforts have freed me from the torment of TAN anymore:)

**Comment by wendall911** [comment]
I literally wrote this mod because of frustration with TAN. I wanted temperature to not be a magic thing, but something that tries to mimic how the human body works (within reason).

**Comment by Windavilin** [comment]
So Homeostatic does!
Expect the new version

**Comment by wendall911** [comment]
Ok, this is up on CurseForge and Modrinth now. Let me know what you think. You'll definitely get hungry from the cold, but at a more reasonable rate now.

**Comment by wendall911** [comment]
After thinking on this a bit, I'm going to override the vanilla behavior for the tag that leather armor uses. It's way too overpowered.
