### ISSUE TITLE
[Suggestion]: Use ForgeGui#rightHeight for overlays to allow for mod compat

### ISSUE THREAD

**Issue by Fuzss** [wendall911/Homeostatic#4]
Hey there, nice mod.

It would be really cool if you could use and update the `ForgeGui#rightHeight` field when drawing your overlays (specifically the hydration and water overlay) instead of only taking vanilla icon offsets into account.
This will allow your overlays to be compatible with other mods that add new/change icon overlays above the hotbar.

There's currently a visual conflict due to this with my Leave My Bars Alone mod: https://github.com/Fuzss/leavemybarsalone/issues/1

Using the Forge field would easily fix that.

**Comment by wendall911** [comment]
Ok, been messing around with this. While, yes, this should return a correct value, it doesn't update until after the custom overlay is rendered :(

It looks like I need to do separate event handler outside of the Forge built-in to do this ... maybe in the POST render ... I have no idea how Forge does this to be honest. I see that theoretically when  renderFood or renderAir should update this value, but it doesn't. I really don't know about rewriting a significant portion of the mod to support this. I know the Forge stuff is supposed to be there to help, but it looks like it actually causes more issues than it solves.

I'll keep playing with this, let me know if you have any suggestions.

**Comment by wendall911** [comment]
Ok, I need to be using registerAbove to get this to work. Looks good now! I'll get this pushed out, thanks for the suggestion. 

Also, great mod, btw. I'm adding it to all my modpacks from here on out.

**Comment by Fuzss** [comment]
Awesome, thank you!

**Comment by wendall911** [comment]
@Fuzss FYI, registerAbove and registerBelow happen before rightHeight is rendered. I think these are really reserved for manipulating Vanilla GUI elements. registerAboveAll and registerBelowAll are what I wanted to target for Mod elements, as they can take advantage of rightHeight. For example, registerAbove (or after) VanillaGuiOverlay.FOOD_LEVEL doesn't provide the updated rightHeight to my overlay element. I didn't bother digging in further to see how the ordering code actually works.

Also, side note: This is so confusing, given that the methods and variables are so poorly named. Above == After and Below == Before in ordering and right/left height deal with the offset for the gui elements. I literally had to go to the Forge source to understand that it is: order and offset, not layer and (whatever rightHeight is supposed to tell me)???!!!

**Comment by Fuzss** [comment]
Yeah well documentation (or more the existence thereof) really is not a strength of Forge haha
This is where the Fabric ecosystem really shines, the documentation over there is amazing

`rightHeight` and `leftHeight` are the names of those fields though as they control the height of icon bars on the right and left side of above the hotbar respectively. So `leftHeight` is for hearts/armor, `rightHeight` is for food/mount health/air meter

And yeah, the above and below naming confused me too, but I think what they are referring to is where you want your icon bar to display relative to the one you're referencing when registering. So if I want my thirst bar to appear above the hunger bar, I need to use `registerAbove`. This is only makes sense for icon rows above the hotbar though, so for any other kind of overlay somewhere on the screen the aboveAll/belowAll methods are probably what I would go for.
