### ISSUE TITLE
Maybe Some more adjustment with Temperature？

### ISSUE THREAD

**Issue by JiuyeAyan** [wendall911/Homeostatic#41]
Thanks for your support on Primal Winter，I'm happy playing with it.
But Something I found I don't know if it is owning to Primal Winter.

1. It's warmer in Frozen Water: 
    It was -17℃ on the ground, however, when I jump into water, the environment rise up to -2℃. Therefore, players will not afraid to hunt under water. And the whole thing is not realistic.
![image](https://github.com/wendall911/Homeostatic/assets/90959597/8ad9232c-6b8e-4d22-bbee-87e4e37025f6)

2. Snow Storm is not scary: 
    The normal temperature is -17℃. While when snow storm is coming, the temperature is just -18℃. What I want to say is the snow storm is not scray enough to prevent players to go out without consideration.
![image](https://github.com/wendall911/Homeostatic/assets/90959597/1859c81e-7b10-49db-8da9-e59912388f5b)
![image](https://github.com/wendall911/Homeostatic/assets/90959597/e65b2ff9-355b-4fb3-bd98-322ca30d06fc)

3. In the 2.9.4.4 Version, I found the hunger is dropping so fast, while I tried 2.9.4.5 version which is  much rational, I appriciate :) And here is the thing, are there any posibility to let myself adjust some parameter in config?

     Because I don't know in what data would make the game funny, maybe i'll test it multiple times.
     1) Parameter to adjust in what body temparature will player reduce HP.
     2) Parameter to adjust the hunger reducing speed.
     3) Parameter to adjust the body temparature dropping speed at day / at night
     4) Parameter to adjust the body temparature dropping speed during the storm, maybe it could be a number that multiply to the normal dropping speed?
     5) Parameter to adjust the Campfire affect range.
     
These are so many changes, and I feel bad asking u to do so much works, it may make you overload, but I really love your mod, I want to play your mod with my friend, I'll do what I can if you need anything.

**Comment by wendall911** [comment]
I'm not trying to dismiss your request, but this is actually really silly. If you started out in a t-shirt in the middle of winter, you'd die within the first day. Asking me to basically make a magical temperature system by basically being able to remove the entire temperature system through configurations is just not going to happen. I know you are trying to make a fun survival experience, but this is just not something that will work well with this mod.

Please read the documentation in the wiki before making more requests on basically what amounts to breaking the mod: https://github.com/wendall911/Homeostatic/wiki/Temperature-Calculations

Primal Winter is a really poorly implemented mod that doesn't really do anything to expose storms, etc. Also, if things are covered in snow, it is WARMER (please look this up, it is basic science). Also, the water, when not frozen is WARMER.

All of the parameters you are requesting would basically just invalidate all of the work to make a balanced mod for 99.99% of people wanting a temperature system that isn't TAN.  I considered the hunger thing a bug. But now it is also nerfed to the point that changing this more will basically just remove the mechanic. Also, changing the body temperature to be something alien just sounds goofy. There are links on the main page, as well as the wiki that explain this.

It sounds like you want a peaceful mode for temperature. That doesn't make sense. The mod should be something folks can react to based on their every day experiences outside. It also uses real body temperature values for a reason. That way all of the math works out. If you start to override basic things, the math no longer works at all. Again, please read the wiki.

Range isn't a thing with thermal radiation. You can increase the thermal radiation of the campfire via datapack. This is also documented in the wiki. There are a lot of things that could have some increases to suit this, like torches.

**Comment by JiuyeAyan** [comment]
Sorry for my dumb askings, it is warmer under water for sure, I should have watch the wiki first.

But I found something today, because, when I create a new world, its -17℃ on the ground, but it's 20+℃ under water, it's totally different from what I have mentiond in this post which have only 1℃ difference. And I was in a very shallow place, like merely burried my head. 

I think this can be a bug?

**Comment by JiuyeAyan** [comment]
> I'm not trying to dismiss your request, but this is actually really silly. If you started out in a t-shirt in the middle of winter, you'd die within the first day. Asking me to basically make a magical temperature system by basically being able to remove the entire temperature system through configurations is just not going to happen. I know you are trying to make a fun survival experience, but this is just not something that will work well with this mod.
> 
> Please read the documentation in the wiki before making more requests on basically what amounts to breaking the mod: https://github.com/wendall911/Homeostatic/wiki/Temperature-Calculations
> 
> Primal Winter is a really poorly implemented mod that doesn't really do anything to expose storms, etc. Also, if things are covered in snow, it is WARMER (please look this up, it is basic science). Also, the water, when not frozen is WARMER.
> 
> All of the parameters you are requesting would basically just invalidate all of the work to make a balanced mod for 99.99% of people wanting a temperature system that isn't TAN. I considered the hunger thing a bug. But now it is also nerfed to the point that changing this more will basically just remove the mechanic. Also, changing the body temperature to be something alien just sounds goofy. There are links on the main page, as well as the wiki that explain this.
> 
> It sounds like you want a peaceful mode for temperature. That doesn't make sense. The mod should be something folks can react to based on their every day experiences outside. It also uses real body temperature values for a reason. That way all of the math works out. If you start to override basic things, the math no longer works at all. Again, please read the wiki.
> 
> Range isn't a thing with thermal radiation. You can increase the thermal radiation of the campfire via datapack. This is also documented in the wiki. There are a lot of things that could have some increases to suit this, like torches.

Sorry for my dumb askings, it is warmer under water for sure, I should have watch the wiki first.

But I found something today, because, when I create a new world, its -17℃ on the ground, but it's 20+℃ under water,  And I was in a very shallow place, like merely burried my head.
Accroding to your calculation formula, it should be (24+17)*0.5 = 20.5℃
I think it is much too warm when it is so close to the surface, what would you think?

**Comment by wendall911** [comment]
It isn't a bug. Winter ground temperatures are around 25C. Water freezes at 0, so if you are in freezing, below 0 temperatures, any liquid water will be warmer. I do the calculation based on the volume of the surrounding water. Yes it is warmer. The on the ground temperature is not related to the underground temperature, which is what affects cold water. This is why only water surfaces freeze in the winter.

The coldest oceans on earth range from -2 to about 10C. Based on the view you've given, all water would be frozen solid. That really makes the game unplayable. I'm not sure primal winter mod should make it colder than the antarctic ocean.

**Comment by JiuyeAyan** [comment]
> It isn't a bug. Winter ground temperatures are around 25C. Water freezes at 0, so if you are in freezing, below 0 temperatures, any liquid water will be warmer. I do the calculation based on the volume of the surrounding water. Yes it is warmer. The on the ground temperature is not related to the underground temperature, which is what affects cold water. This is why only water surfaces freeze in the winter.
> 
> The coldest oceans on earth range from -2 to about 10C. Based on the view you've given, all water would be frozen solid. That really makes the game unplayable. I'm not sure primal winter mod should make it colder than the antarctic ocean.

Oh, I've learned alot, you did really good :)

![image](https://github.com/wendall911/Homeostatic/assets/90959597/1e045c41-0140-4cdc-979e-e807e8469ffc)
But I still think we should check this picture? my body temperature is 96℃, and I touched the water only by foot, then the environment temperature is 19℃..... oh..... I think you mean the 19℃ is the water temperature, it's no longer the air temperature when I touch water... is that right?

**Comment by JiuyeAyan** [comment]
> It isn't a bug. Winter ground temperatures are around 25C. Water freezes at 0, so if you are in freezing, below 0 temperatures, any liquid water will be warmer. I do the calculation based on the volume of the surrounding water. Yes it is warmer. The on the ground temperature is not related to the underground temperature, which is what affects cold water. This is why only water surfaces freeze in the winter.
> 
> The coldest oceans on earth range from -2 to about 10C. Based on the view you've given, all water would be frozen solid. That really makes the game unplayable. I'm not sure primal winter mod should make it colder than the antarctic ocean.

Oh, I've learned alot, you did really good :)

![image](https://github.com/wendall911/Homeostatic/assets/90959597/c5aadba4-693f-4699-8675-8ade79b827fa)
But I still think we should check this picture? my body temperature is 98.5℃, and I touched the water only by foot, then the environment temperature is 18℃..... oh..... I think you mean the 18℃ is the water temperature, it's no longer the air temperature when I touch water... is that right?

**Comment by wendall911** [comment]
For some reason I don't see your last question. Yes, being in water has different calculations, but one is for partial submersion, the second is for full submersion. So even if you are partially in water, it affects the temperature. This is also true if not playing Primal Winter and in a desert environment where it is really warm.

I know it is counterintuitive, but water, when not frozen can be warming (even if you'll freeze to death in a short amount of time).

**Comment by wendall911** [comment]
Oh, I haven't included the body calculation stuff. I will add to the Wiki when I have time. It is pretty complicated. Does different stuff in many different situations.

**Comment by JiuyeAyan** [comment]
> Oh, I haven't included the body calculation stuff. I will add to the Wiki when I have time. It is pretty complicated. Does different stuff in many different situations.

Thank u, I just feel that I'll still making dumb questions so I deleted my post, I've learnd alot from u, thanks for your kind and patience :)
