### ISSUE TITLE
Villagers from Minecraft Comes Alive immediately start taking damage

### ISSUE THREAD

**Issue by scribe-of-days** [wendall911/Homeostatic#44]
Hey there! I love the mod and appreciate you making it. Earlier today I was testing out MCA and its villagers and realized when I put down a spawn egg that the villager that appeared (a custom mob, not a typical villager) began taking damage very quickly. I think this is probably because they spawned in with an empty thirst bar. Is there some way you could exempt NPCs from thirst and temperature requirements generally? I suspect the same issue might be true with Minecolonies NPCs too but I haven't been able to test them yet, as Minecolonies doesn't have a spawn egg I can easily throw down. 

Thanks again!

**Comment by wendall911** [comment]
I don't think this has anything to do with the mod. When you see the water dropplets popping up around them it is because they are sad.

**Comment by wendall911** [comment]
Just give the newly spawned in villager a hug! They will stop crying.
