### ISSUE TITLE
Would you please consider making this mod compatible with TFC:TNG?

### ISSUE THREAD

**Issue by wglpython** [wendall911/Homeostatic#45]
In TFC:TNG, the environmental temperature does not affect the temperature calculation of this mod. I am aware that TFC:TNG had a companion temperature mod called TFCAmbiental, but the author of that mod has discontinued support and it has numerous bugs. I would like to propose using Homeostatic as an alternative. I'm using version 1.18.2, and I kindly request the author to consider my suggestion. I apologize if my request comes across as offensive.

**Comment by wglpython** [comment]
https://www.curseforge.com/minecraft/mc-mods/terrafirmacraft
thats TFC:TNG

**Comment by wendall911** [comment]
Sorry for being so slow. TNC is a good concept, but it isn't a really great mod to add integration to. They do a lot of silly things, like overriding the menus and having a semi-working temperature/thirst system. I can't see any way to do this well.
