### ISSUE TITLE
Parent loop delaying startup

### ISSUE THREAD

**Issue by Jadan1213** [wendall911/Homeostatic#48]
I get this message every time the game starts, and it delays bootup.

Found 'parent' loop while loading model 'homeostatic:block/purified_water_fluid' in chain: homeostatic:block/purified_water_fluid -> homeostatic:block/purified_water_fluid

**Comment by wendall911** [comment]
This is a Forge datagen bug. I manually fixed it (1.19.2). Won't be an issue in 1.20.1 and beyond.

**Comment by Jadan1213** [comment]
I am on 1.20.1 actually

**Comment by wendall911** [comment]
Try the latest version, should be resolved.

**Comment by Jadan1213** [comment]
All right no problem, I plan to update due to the water quantity fix when I get a chance. 

It's been a while since I've looked at the log so it could have been in the last update you made too and I just never looked to notice it
