### ISSUE TITLE
purified water duplication

### ISSUE THREAD

**Issue by Jadan1213** [wendall911/Homeostatic#49]
when used with refined storage, the water from the flask can be put into storage. 

It takes 1 bucket worth of water to fill a flask, but the flask contains 5 buckets worth of water. 

When you place this water into refined storage, it stores 5 buckets, which can then be removed individually, placed down, and can be used to refill the flask 5 times. Each refill being able to be duplicated again if the steps are repeated.

I believe the flask should be changed from 5000, to 1000, and have each drink from it be reduced proportionally to prevent this duping.

**Comment by Jadan1213** [comment]
or changed from uses per amount of water stored, to just individual uses available without technically storing the water.

**Comment by wendall911** [comment]
Ok, that makes a lot of sense. Let me take a look and see what I can do. I can't remember why I set it to 5000mb.
