### ISSUE TITLE
Crash 1.19.2 forge 43.1.43 

### ISSUE THREAD

**Issue by Thisguyneedshelp** [wendall911/Homeostatic#5]
https://mclo.gs/0eFaAiQ

**Comment by Thisguyneedshelp** [comment]
its because of bop updating, idk if it needs they need to fix it or what.

**Comment by wendall911** [comment]
Ok, thank you for the head's up. I'll get a fix out shortly.

**Comment by wendall911** [comment]
Fixed in latest: https://www.curseforge.com/minecraft/mc-mods/homeostatic/files/4032670

I updated so if they break the API again, it should still function.

**Comment by wendall911** [comment]
By the way, they removed a biome that was a part of their API. I am not relying on their API as much now knowing they push out breaking changes for the same minecraft version.
