### ISSUE TITLE
Origin mod compat

### ISSUE THREAD

**Issue by AnterCreeper** [wendall911/Homeostatic#50]
https://www.curseforge.com/minecraft/mc-mods/origins-forge
https://www.curseforge.com/minecraft/mc-mods/origins-classes-forge

**Comment by wendall911** [comment]
I'm not sure what this request means. Can you provide more information?

**Comment by wendall911** [comment]
Closing this, as I've asked other devs, and unless there is some suggestions for integration, I'm going to close this for now.
