### ISSUE TITLE
Namespace change of the Fruitful Fun mod (previously Fruit Trees)

### ISSUE THREAD

**Issue by Snownee** [wendall911/Homeostatic#51]
Just a friendly reminder that the namespace of the Fruit Trees mod has been changed from `fruittrees` to `fruitfulfun` since 1.20.1, so the integration in this mod may no longer work.

**Comment by wendall911** [comment]
Oh, thanks for the note! I am just starting work on multiloader for this mod. I am still unsure if I jump straight to 1.20.6, or provide a 1.20.4. But will make the change for certain.

**Comment by wendall911** [comment]
I will also make the change in 1.20.1 to support this correctly.  SurvivalistEssentials will also need the change to support the wood products.
