### ISSUE TITLE
Shift-Clicking Into Furnaces Crashes the Game

### ISSUE THREAD

**Issue by CraftyZombie** [wendall911/Homeostatic#54]
In Homeostatic's most recent update, shift-clicking into a furnace crashes the game. Moving the item manually, however, doesn't.

Versions:
Forge: 47.3.4
Homeostatic: 2.9.6.0
Minecraft: 1.20.1

Logs and Crash Report:
https://gist.github.com/CraftyZombie/24205953c2770772ce6b73bcc51a0e43

**Comment by wendall911** [comment]
Ok, this is fixed and pushed to Curseforge/Modrinth

**Comment by CraftyZombie** [comment]
Thank you so much!
