### ISSUE TITLE
Furnace crash

### ISSUE THREAD

**Issue by Arch23-tech** [wendall911/Homeostatic#55]
For some weird reason my furnace kept crashing my game while using this mod ... when I removed this mod it stopped crashing whenever I open my furnace UI.

I don't know what is the relation between this mod and how furnaces work but I hope it is fixed somehow 😅..

Thanks for the creator of this jaw breaking mod ... it is so stable and realistic better than (tough as nails) and (cold sweat) in my opinion.

Keep going 👍

**Comment by wendall911** [comment]
Please update to the latest! I just fixed this morning. Duplicate #54

**Comment by wendall911** [comment]
Can you confirm if my update worked for you? Just want to make sure before I close this. It was related to moving to multi-loader platform so I can also support Fabric. Luckily, this was my only major bug!

**Comment by Arch23-tech** [comment]
Yes, it worked! Thanks

Everything going as great as the mod itself

**Comment by wendall911** [comment]
Ok, awesome, let me know if you find any other issues.
