### ISSUE TITLE
Unable to access creative gamemod inventory

### ISSUE THREAD

**Issue by Leiriad** [wendall911/Homeostatic#57]
I have this issue in the 1.21 modpack I'm trying to build. The game plays fine in survival, but if I'm in creative mode and press E to get to the inventory, my game crashes. The report says something about the leather-flask item. I don't have one in my inventory, it is empty as I've just launched a new game.

[crash-2024-07-15_19.09.41-client.txt](https://github.com/user-attachments/files/16238093/crash-2024-07-15_19.09.41-client.txt)

Beside, is there a way to make the recipe of the flask and first insulated equipement easier? I started in a snowy biome, there were 3 cows and no sheep... I kept dying over and over again.

**Comment by wendall911** [comment]
Oh, damn. I intentionally disable the mod in creative. This was not the intended way to disable though. I'll push out a fix shortly and let you know. Thanks for reporting!

**Comment by wendall911** [comment]
The flask isn't the only way to drink water. Sneak and right click on an open water source. I would say look in the book, but Patchouli isn't updated for 1.21 yet.

**Comment by wendall911** [comment]
Also, just an aside. If working on a modpack, I strongly suggest not using creative mode when configuring things. It is a really bad way to do testing. Install JEI and add at shortcut to toggle on cheats in Survival. Trust me, your modpack will work better and you'll avoid a lot of issues. Creative mode is just terrible for a lot of mods. I really wish that NeoForge/Fabric gave a way to entirely disable a mod from Creative and Spectator entirely. It is very problematic to be honest, as things just work differently. Historically, Notch didn't want it at all, but was pressured by YouTubers to keep it. I honestly wish it didn't exist, as it actually breaks a lot of stuff.

**Comment by wendall911** [comment]
Ok, it's up on CurseForge and Modrinth!

One other note about the flask and leather. What we do in our modpacks is add a recipe for leather: https://github.com/wendall911/TinkerSurvivalModpack/blob/1.19.2/scripts/AdditionalRecipes.zs (The cooked meat stuff) This isn't super hard to do, but will take some work. There are mods that add leather alternatives as well. You can also change the recipe via datapack. Nearly everything in Homeostatic can be overridden via datapack.
