### ISSUE TITLE
Is there compatibility with Fabric Seaons or Simple Seasons?

### ISSUE THREAD

**Issue by eliasjurkeit** [wendall911/Homeostatic#60]
In the modrinth description you said:
> Seasons are taken into account if using Serene Seasons. (At least until there is a viable season alternative).

I think that Fabric Seaons and Simple Seasons are both worthy / even better alternatives.

**Comment by wendall911** [comment]
Fabric Seasons is supported on all versions it has releases for. Simple seasons only has one version for 1.20.1, so I won't support it, as it is just a one-off release. I wrote that when Fabric Seasons didn't have a stable release. Now they seem to have unfortunately abandoned development.
