### ISSUE TITLE
Food Items with Cropttopia

### ISSUE THREAD

**Issue by makumaku1974** [wendall911/Homeostatic#62]
Such food items related to fruits, meat, and vegetables contains some minor buffs or debuffs once consumed.

**Comment by makumaku1974** [comment]
Fruits can be well hydrated, meat can dehydrate quickly, veggies have the balance of both.

**Comment by wendall911** [comment]
This is already a feature. Depending on the food it provides some hydration. I'm not sure I understand this request.

**Comment by makumaku1974** [comment]
Could this work with the mod croptopia?

**Comment by wendall911** [comment]
It works currently with Croptopia.

**Comment by wendall911** [comment]
There is a hydration preview if holding a food item that shows how much hydration it will restore. Just eat some fruit and see how it works.

**Comment by makumaku1974** [comment]
what version of croptopia is it supported? i think i have the oldest version of croptopia

**Comment by wendall911** [comment]
All versions.

**Comment by wendall911** [comment]
I'm going to close this issue. Just install the mods and check yourself. It takes just a couple minutes.
