### ISSUE TITLE
[Suggestion] Compatibility with Terralith

### ISSUE THREAD

**Issue by Leiriad** [wendall911/Homeostatic#63]
Terralith, like Biomes O'Plenty is a frequently used generation mod. A compatibility with it could be very appreciated.

**Comment by wendall911** [comment]
Added for 1.21 and 1.21.1 I really don't like Terralith, as it is very low code quality mod. Missing lots of definitions, translations, etc. But it's popular *shrugs* ... 

Let me know if you need for older versions. I can probably backport.

**Comment by Leiriad** [comment]
My modpack is in 1.20.1, so if you don't mind, it would be great to have a 1.20.1 version.

**Comment by wendall911** [comment]
Ok, I released for 1.20.1. On CurseForge and Modrinth
