### ISSUE TITLE
[Suggestion] Place Homeostatic Tome in a chiseled bookshelf

### ISSUE THREAD

**Issue by ozBillo** [wendall911/Homeostatic#69]
Allow Homeostatic Tome to be placed in a chiseled bookshelf

**Comment by wendall911** [comment]
I'm not sure if it is possible with Patchouli books. I'll take a look and see if it is.

**Comment by wendall911** [comment]
Ok, added in the latest release.

**Comment by wendall911** [comment]
Note: for 1.21.1 only.

**Comment by ozBillo** [comment]
Any chance you could add it to 1.20.1?

**Comment by wendall911** [comment]
I can add for 1.20.1. I am working on backporting the latest changes.  I'll comment here when I have it updated.

**Comment by wendall911** [comment]
Backported to 1.20.1. Released on CurseForge and Modrinth

**Comment by ozBillo** [comment]
Thank you 😊
