### ISSUE TITLE
[Bug/Request?] Thirst/Temperature continues while not in survival gamemode

### ISSUE THREAD

**Issue by Tellik** [wendall911/Homeostatic#7]
Thirst and temperature changes while in creative mode, which makes it difficult for testing when I need to switch from creative into survival and instantly die due to hypothermia or dehydration. Also makes it a little tricky to see when I get the hypothermia screen effects while in creative. Oh, also effects the player while in spectator mode.

If it's fairly easy to disable/pause while in creative/spectator, that would be great. It's not a huge priority, and I want to keep the mod enabled while I'm testing the pack to keep track of any issues or conflicts.

**Comment by wendall911** [comment]
I'll fix this. I noticed this while creating the book. I must have broken this with another change. The only thing that should work is the debugging display (if enabled).

**Comment by wendall911** [comment]
The latest versions for 1.18.2 and 1.19+ on CurseForge have this fix in. Thanks again for the report.

**Comment by Tellik** [comment]
No worries, here to help.
