### ISSUE TITLE
[BUG] Vampirism incompatibility

### ISSUE THREAD

**Issue by schindlershadow** [wendall911/Homeostatic#77]
Vampirism hud overwrites the temperature and water hud
https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire
![2024-10-13_21 13 03](https://github.com/user-attachments/assets/e3183c54-c61b-4bf1-b883-54e1548c971a)

**Comment by wendall911** [comment]
This is a Vampirism bug, but I'll see if I can work around it. Since you didn't leave any details, can you please provide the versions and the loader? I literally am unable to guess from a screenshot.

**Comment by schindlershadow** [comment]
neoforge 21.1.61
vampirism 1.10.0
Homeostatic 2.9.11.2

**Comment by wendall911** [comment]
This is fixed in the latest release. Can be found on CurseForge and Modrinth.
