### ISSUE TITLE
[Suggestion] Vampirism compatibility

### ISSUE THREAD

**Issue by schindlershadow** [wendall911/Homeostatic#78]
compatibility with Vampirism 
https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire

suggestions

1. vampires are not affected by freezing
2. vampires either do not need water or it is shared with the blood bar somehow
3. vampires have different body temperature 
4. vampires are affected by heat/scalding more drastically

**Comment by wendall911** [comment]
I'll take a look, thanks for the suggestion.

**Comment by wendall911** [comment]
I'm not sure of a way to do this that makes any sense. This entire mod is designed to work with human body temperatures. I think the best I can do is just disable the mod features if affected by vampirism. I'm not really very interested in support without having full details of how it would even be fun gameplay to integrate temperature. Thirst isn't even an issue, as they have a different biology.

**Comment by schindlershadow** [comment]
disabling the features would work

**Comment by wendall911** [comment]
This is fixed in the latest release. Can be found on CurseForge and Modrinth.
