### ISSUE TITLE
Add Terrafermacraft compatibility 

### ISSUE THREAD

**Issue by 2Silver1** [wendall911/Homeostatic#79]
I’m wondering if this is compatible with TFC(Terrafermacraft)? If not, I’m wondering if you could point me toward making them work. 

In advance, thanks a lot for helping out.

**Comment by wendall911** [comment]
It is not compatible at the moment. I can take a look at compat for 1.20.1 and see what I can come up with.

**Comment by wendall911** [comment]
There isn't any way that these can be compatible. Terrafirmacraft has its own temperature and thirst system. I won't be able to add any support.

**Comment by 2Silver1** [comment]
> There isn't any way that these can be compatible. Terrafirmacraft has its own temperature and thirst system. I won't be able to add any support.

That sucks, I had a feeling you couldn’t, thanks for checking it out.
